export const EDUCATION_TIPS = [
    "Test yourself before the exam does.",
    "Recall is stronger than review.",
    "Spaced repetition is the cheat code to memory.",
    "Teach it to a 5-year-old to find the gaps in your knowledge.",
    "Friction is a sign of learning. Don't avoid it.",
    "Sleep is when your brain saves the file.",
    "Highlighting is passive. Questioning is active.",
    "Don't study until you get it right. Study until you can't get it wrong.",
    "The hardest subjects require the shortest study intervals.",
    "Your environment dictates your focus.",
    "If you can't explain it simply, you don't understand it well enough.",
    "Mistakes are just data. Collect them and adjust.",
    "Consistency beats intensity every time.",
    "Break big concepts into molecular pieces.",
    "Don't read the textbook. Interrogate it.",
    "Start with the hardest task when your willpower is highest.",
    "You don't rise to the level of your goals, you fall to the level of your systems.",
    "A 15-minute daily habit beats a 5-hour cram session.",
    "Anxiety is often just under-preparation in disguise.",
    "Action creates momentum. Momentum creates results.",
    "Your brain is a muscle. Progressive overload applies to learning.",
    "Take breaks before you need them.",
    "Don't confuse recognition with understanding.",
    "Use analogies to anchor new concepts to old ones.",
    "Test your memory, don't just re-read the page.",
    "Distraction is the enemy of retention.",
    "Learn the rules like a pro, so you can break them like an artist.",
    "The obstacle in your understanding is the path to mastery.",
    "Review your notes within 24 hours to halt the forgetting curve.",
    "Every master was once a beginner.",
    "Focus on the process, not the grade.",
    "Learning should feel slightly uncomfortable.",
    "Visualize the concept, don't just memorize the words.",
    "Curiosity accelerates retention.",
    "Write down what you don't know.",
    "Don't study for the test, study for mastery.",
    "Knowledge compounds. Keep investing.",
    "Embrace the struggle. It means your brain is rewiring.",
    "Study with intent. Casual reading is not studying.",
    "Your mindset determines your ceiling.",
    "Find the pattern, not just the isolated fact.",
    "Connect new information to something you already care about.",
    "The more you test, the less you stress.",
    "Don't wait for motivation. Create discipline.",
    "Focus is a skill. Train it daily.",
    "Read actively: ask questions as you go.",
    "The best time to start was yesterday. The next best time is now.",
    "Small daily improvements lead to massive long-term results.",
    "If it's easy, you're not growing.",
    "Master the fundamentals before chasing advanced topics.",
    "Learning is a marathon, not a sprint.",
    "Your potential is limited only by your persistence.",
    "Doubt kills more dreams than failure ever will.",
    "The secret to getting ahead is getting started.",
    "Don't let what you cannot do interfere with what you can do.",
    "Strive for progress, not perfection.",
    "The only bad study session is the one that didn't happen.",
    "Your future self is watching you right now through memories.",
    "Knowledge is power, but action is the switch.",
    "If you want different results, do something different.",
    "Discipline equals freedom.",
    "Don't limit your challenges. Challenge your limits.",
    "The expert in anything was once a beginner.",
    "You fail only when you stop trying.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Believe you can and you're halfway there.",
    "Success is the sum of small efforts, repeated day-in and day-out.",
    "Fall seven times, stand up eight.",
    "The difference between ordinary and extraordinary is that little extra.",
    "If you are not willing to learn, no one can help you.",
    "If you are determined to learn, no one can stop you.",
    "Every day is a new opportunity to change your life.",
    "Make your life a masterpiece; imagine no limitations.",
    "Challenges are what make life interesting.",
    "Overcoming challenges is what makes life meaningful.",
    "Do what is right, not what is easy.",
    "Your attitude determines your direction.",
    "The best way to predict your future is to create it.",
    "Hard work beats talent when talent doesn't work hard.",
    "Dream big and dare to fail.",
    "Education is the most powerful weapon.",
    "Learning never exhausts the mind.",
    "An investment in knowledge pays the best interest.",
    "The beautiful thing about learning is nobody can take it away.",
    "Live as if you were to die tomorrow. Learn as if you were to live forever.",
    "Develop a passion for learning.",
    "Wisdom is not a product of schooling but of the lifelong attempt to acquire it.",
    "The mind is not a vessel to be filled, but a fire to be kindled.",
    "Education is the passport to the future.",
    "The roots of education are bitter, but the fruit is sweet.",
    "Learning is an active process. We learn by doing.",
    "Tell me and I forget, teach me and I may remember, involve me and I learn.",
    "Change is the end result of all true learning.",
    "The more that you read, the more things you will know.",
    "You don't have to be great to start, but you have to start to be great.",
    "Preparation is the key to success.",
    "Study hard, no matter if it seems impossible.",
    "The secret of success is to do the common things uncommonly well.",
    "Success doesn't come to you, you go to it.",
    "There are no shortcuts to any place worth going."
];

export function getDailyTip(userId: string): string {
    if (!userId) return EDUCATION_TIPS[0];
    
    // Create a stable daily index for this user
    // Combine user ID and current date string to get a unique hash per user per day
    const dateStr = new Date().toISOString().split("T")[0];
    const hashString = `${userId}-${dateStr}`;
    
    let hash = 0;
    for (let i = 0; i < hashString.length; i++) {
        hash = ((hash << 5) - hash) + hashString.charCodeAt(i);
        hash |= 0; // Convert to 32bit int
    }
    
    const index = Math.abs(hash) % EDUCATION_TIPS.length;
    return EDUCATION_TIPS[index];
}
