// Static imports removed for bundle size optimization
// Using dynamic imports within functions

export interface PDFExportOptions {
    title: string;
    filename: string;
    author?: string;
    themeColor?: string;
}

/**
 * High-fidelity PDF Bridge
 * Uses jsPDF for document structure and html2canvas for rich component rendering.
 */
export async function exportToPDF(elementId: string, options: PDFExportOptions): Promise<void> {
    const element = document.getElementById(elementId);
    if (!element) {
        throw new Error(`Element with id "${elementId}" not found for PDF export.`);
    }

    try {
        const html2canvas = (await import("html2canvas")).default;
        
        // Use a more robust import for jsPDF to avoid Turbopack HMR factory issues
        const { jsPDF } = await import("jspdf");

        // Optimize for high-fidelity capture
        const canvas = await html2canvas(element, {
            scale: 2, // Higher density for crisp text
            useCORS: true,
            backgroundColor: "#040406", // Deep brand black
            logging: false,
            onclone: (clonedDoc) => {
                const el = clonedDoc.getElementById(elementId);
                if (el) {
                    el.style.display = "block";
                    el.style.padding = "40px";
                    
                    // Inject professional watermark into the clone
                    const watermark = clonedDoc.createElement("div");
                    watermark.style.position = "fixed";
                    watermark.style.top = "50%";
                    watermark.style.left = "50%";
                    watermark.style.transform = "translate(-50%, -50%) rotate(-30deg)";
                    watermark.style.fontSize = "40px";
                    watermark.style.fontWeight = "900";
                    watermark.style.color = "rgba(245, 158, 11, 0.02)";
                    watermark.style.zIndex = "0";
                    watermark.style.pointerEvents = "none";
                    watermark.style.whiteSpace = "nowrap";
                    watermark.style.textTransform = "uppercase";
                    watermark.style.letterSpacing = "1em";
                    watermark.innerHTML = "THE PROFESSOR AI • VERIFIED INTELLECTUAL ASSET";
                    el.appendChild(watermark);

                    // Add branding badge to the top right
                    const badge = clonedDoc.createElement("div");
                    badge.style.position = "absolute";
                    badge.style.top = "40px";
                    badge.style.right = "40px";
                    badge.style.padding = "8px 16px";
                    badge.style.borderRadius = "12px";
                    badge.style.background = "rgba(245, 158, 11, 0.1)";
                    badge.style.border = "1px solid rgba(245, 158, 11, 0.2)";
                    badge.style.color = "#F59E0B";
                    badge.style.fontSize = "10px";
                    badge.style.fontWeight = "900";
                    badge.style.textTransform = "uppercase";
                    badge.style.letterSpacing = "0.2em";
                    badge.innerHTML = "Verified Capture";
                    el.appendChild(badge);

                    // Add branding footer to the clone
                    const footer = clonedDoc.createElement("div");
                    footer.style.marginTop = "80px";
                    footer.style.paddingTop = "30px";
                    footer.style.borderTop = "1px solid rgba(255, 255, 255, 0.1)";
                    footer.style.display = "flex";
                    footer.style.justifyContent = "space-between";
                    footer.style.alignItems = "center";
                    footer.style.color = "rgba(255, 255, 255, 0.3)";
                    footer.style.fontSize = "10px";
                    footer.style.fontWeight = "bold";
                    footer.style.textTransform = "uppercase";
                    footer.style.letterSpacing = "0.2em";
                    footer.innerHTML = `
                        <div style="display: flex; align-items: center; gap: 10px;">
                            <div style="width: 24px; height: 24px; background: #F59E0B; border-radius: 6px; display: flex; align-items: center; justify-content: center; color: black; font-weight: 900;">P</div>
                            <span>Generated by The Professor AI Platform</span>
                        </div>
                        <div>theprofessor.xyz</div>
                    `;
                    el.appendChild(footer);
                }
            }
        });

        const imgData = canvas.toDataURL("image/png");
        const pdf = new jsPDF({
            orientation: "portrait",
            unit: "mm",
            format: "a4"
        });

        const imgProps = pdf.getImageProperties(imgData);
        const pdfWidth = pdf.internal.pageSize.getWidth();
        const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;

        // Add metadata
        pdf.setProperties({
            title: options.title,
            subject: "Academic Strategy Material",
            author: options.author || "The Professor",
            creator: "The Professor AI Intelligence Platform"
        });

        // Add the image to PDF
        pdf.addImage(imgData, "PNG", 0, 0, pdfWidth, pdfHeight, undefined, "FAST");

        // Save
        const safeFilename = options.filename.replace(/[^a-z0-9]/gi, '_').toLowerCase();
        pdf.save(safeFilename.endsWith(".pdf") ? safeFilename : `${safeFilename}.pdf`);
        
    } catch (error) {
        console.error("PDF Export failed:", error);
        throw error;
    }
}

/**
 * Utility to generate a PDF from raw markdown or text (fallback/simpler version)
 */
export async function exportMarkdownToPDF(title: string, content: string, filename: string): Promise<void> {
    const { jsPDF } = await import("jspdf");
    const pdf = new jsPDF();
    
    // Simple layout - real implementation should use a hidden ref to render markdown to HTML first
    pdf.setFontSize(22);
    pdf.setTextColor(245, 158, 11); // Amber
    pdf.text(title, 20, 20);
    
    pdf.setFontSize(12);
    pdf.setTextColor(0, 0, 0);
    
    // Split text into lines that fit the page width
    const splitText = pdf.splitTextToSize(content, 170);
    pdf.text(splitText, 20, 40);
    
    pdf.save(filename.endsWith(".pdf") ? filename : `${filename}.pdf`);
}
