export const ACADEMIC_QUOTES = [
    { text: "The impediment to action advances action. What stands in the way becomes the way.", author: "Marcus Aurelius" },
    { text: "It is not that we have a short time to live, but that we waste a lot of it.", author: "Seneca" },
    { text: "Education is not the learning of facts, but the training of the mind to think.", author: "Albert Einstein" },
    { text: "The beautiful thing about learning is that no one can take it away from you.", author: "B.B. King" },
    { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
    { text: "I have never let my schooling interfere with my education.", author: "Mark Twain" },
    { text: "Learning is not attained by chance, it must be sought for with ardor and attended to with diligence.", author: "Abigail Adams" },
    { text: "We suffer more often in imagination than in reality.", author: "Seneca" },
    { text: "He who has a why to live for can bear almost any how.", author: "Friedrich Nietzsche" },
    { text: "Do not say a little in many words but a great deal in a few.", author: "Pythagoras" },
    { text: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
    { text: "Wonder is the beginning of wisdom.", author: "Socrates" },
    { text: "No man's knowledge here can go beyond his experience.", author: "John Locke" },
    { text: "To acquire knowledge, one must study; but to acquire wisdom, one must observe.", author: "Marilyn vos Savant" },
    { text: "If you think education is expensive, try ignorance.", author: "Derek Bok" },
    { text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
    { text: "Education is the passport to the future, for tomorrow belongs to those who prepare for it today.", author: "Malcolm X" },
    { text: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle" },
    { text: "A mind that is stretched by a new experience can never go back to its old dimensions.", author: "Oliver Wendell Holmes Jr." },
    { text: "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.", author: "Colin Powell" },
    { text: "Success is the sum of small efforts, repeated day-in and day-out.", author: "Robert Collier" },
    { text: "Genius is 1% inspiration and 99% perspiration.", author: "Thomas Edison" },
    { text: "The expert in anything was once a beginner.", author: "Helen Hayes" },
    { text: "Wisdom begins in wonder.", author: "Socrates" },
    { text: "Study without desire spoils the memory, and it retains nothing that it takes in.", author: "Leonardo da Vinci" },
    { text: "Knowledge is power.", author: "Francis Bacon" },
    { text: "They cannot stop me. I will get my education, if it is in the home, school, or anyplace.", author: "Malala Yousafzai" },
    { text: "The whole purpose of education is to turn mirrors into windows.", author: "Sydney J. Harris" },
    { text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela" },
    { text: "A reader lives a thousand lives before he dies. The man who never reads lives only one.", author: "George R.R. Martin" },
    { text: "You don't understand anything until you learn it more than one way.", author: "Marvin Minsky" },
    { text: "Real learning comes about when the competitive spirit has ceased.", author: "Jiddu Krishnamurti" },
    { text: "Learning never exhausts the mind.", author: "Leonardo da Vinci" },
    { text: "The more that you read, the more things you will know. The more that you learn, the more places you'll go.", author: "Dr. Seuss" },
    { text: "Anyone who stops learning is old, whether at twenty or eighty. Anyone who keeps learning stays young.", author: "Henry Ford" },
    { text: "Change is the end result of all true learning.", author: "Leo Buscaglia" },
    { text: "Education without values, as useful as it is, seems rather to make man a more clever devil.", author: "C.S. Lewis" },
    { text: "Intelligence plus character—that is the goal of true education.", author: "Martin Luther King Jr." },
    { text: "You can teach a student a lesson for a day; but if you can teach him to learn by creating curiosity, he will continue the learning process as long as he lives.", author: "Clay P. Bedford" },
    { text: "Tell me and I forget, teach me and I may remember, involve me and I learn.", author: "Benjamin Franklin" },
    { text: "In learning you will teach, and in teaching you will learn.", author: "Phil Collins" },
    { text: "The mind is not a vessel to be filled, but a fire to be kindled.", author: "Plutarch" },
    { text: "A well-educated mind will always have more questions than answers.", author: "Helen Keller" },
    { text: "The great aim of education is not knowledge but action.", author: "Herbert Spencer" },
    { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { text: "Whatever you are, be a good one.", author: "Abraham Lincoln" },
    { text: "Patience, persistence and perspiration make an unbeatable combination for success.", author: "Napoleon Hill" },
    { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Will Durant (interpreting Aristotle)" },
    { text: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson" },
    { text: "If we knew what it was we were doing, it would not be called research, would it?", author: "Albert Einstein" },
];

export function getRandomQuote() {
    return ACADEMIC_QUOTES[Math.floor(Math.random() * ACADEMIC_QUOTES.length)];
}
