"use client";

import React from "react";

interface PrintLayoutProps {
    data: {
        title: string;
        count: number | string;
        type: string;
        user: string;
        items?: any[];
        date?: string;
    };
}

/**
 * Premium Print Layout for high-fidelity PDF generation.
 * This component is intended to be rendered hiddenly and captured by html2canvas.
 */
export default function PrintLayout({ data }: PrintLayoutProps) {
    const isQuiz = data.type.toLowerCase() === 'quiz';
    const items = data.items || [];
    const today = data.date || new Date().toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
    });

    return (
        <div 
            id="pdf-export-container"
            className="p-12 bg-white text-slate-900 font-sans w-[210mm] min-h-[297mm] flex flex-col"
            style={{ display: "none" }} // Hidden by default, cloned for capture
        >
            {/* Header Area */}
            <div className="border-b-4 border-[var(--accent)] pb-8 mb-10 flex justify-between items-end">
                <div>
                    <h1 className="text-4xl font-black text-black leading-tight uppercase tracking-tight">{data.title}</h1>
                    <p className="text-xs font-bold text-slate-400 mt-2 uppercase tracking-[0.2em]">
                        {data.type} &bull; {data.count} Items &bull; Generated by {data.user}
                    </p>
                </div>
                <div className="text-right">
                    <p className="text-[10px] font-black uppercase text-slate-300 tracking-widest">{today}</p>
                    <p className="text-xs font-bold text-[var(--accent)]">THE PROFESSOR</p>
                </div>
            </div>

            {/* Content Area */}
            <div className="flex-1 space-y-8">
                {items.map((item, idx) => (
                    <div 
                        key={idx} 
                        className={isQuiz ? "break-inside-avoid pb-4" : "break-inside-avoid p-6 rounded-2xl bg-slate-50 border border-slate-100"}
                    >
                        {isQuiz ? (
                            <div className="space-y-4">
                                <div className="flex gap-4">
                                    <span className="flex-shrink-0 w-8 h-8 rounded-full bg-slate-900 text-white flex items-center justify-center font-black text-sm">
                                        {idx + 1}
                                    </span>
                                    <p className="font-bold text-lg leading-snug pt-0.5">{item.question}</p>
                                </div>
                                <div className="grid grid-cols-2 gap-3 ml-12">
                                    {item.options?.map((opt: string, i: number) => (
                                        <div key={i} className="p-3 rounded-xl border border-slate-200 text-sm font-medium bg-white flex items-center gap-3">
                                            <span className="text-[10px] font-black text-slate-300 w-4">{String.fromCharCode(65 + i)}</span>
                                            {opt}
                                        </div>
                                    ))}
                                </div>
                            </div>
                        ) : (
                            <div className="space-y-4">
                                <div className="text-[10px] font-black text-[var(--accent)] uppercase tracking-widest">Flashcard {idx + 1}</div>
                                <div className="text-lg font-bold text-slate-900 leading-snug">{item.front}</div>
                                <div className="pt-4 border-t border-slate-200 text-slate-600 text-sm leading-relaxed italic">
                                    {item.back}
                                </div>
                            </div>
                        )}
                    </div>
                ))}
            </div>

            {/* Answer Key (for Quizzes) */}
            {isQuiz && (
                <div className="mt-16 pt-12 border-t-2 border-dashed border-slate-200 break-before-page">
                    <h2 className="text-2xl font-black mb-8 uppercase tracking-tight text-slate-400">Answer Key</h2>
                    <div className="grid grid-cols-5 gap-4 mb-12">
                        {items.map((item, idx) => (
                            <div key={idx} className="flex items-center gap-2">
                                <span className="text-[10px] font-black text-slate-300">{idx + 1}.</span>
                                <span className="font-bold text-slate-900">{String.fromCharCode(65 + item.correctIndex)}</span>
                            </div>
                        ))}
                    </div>
                    <div>
                        <h3 className="text-sm font-black mb-4 uppercase text-slate-400">Explanations</h3>
                        <div className="space-y-4">
                            {items.map((item, idx) => (
                                <p key={idx} className="text-xs text-slate-500 leading-relaxed font-medium">
                                    <span className="font-black text-slate-900 mr-1">{idx + 1}.</span> {item.explanation}
                                </p>
                            ))}
                        </div>
                    </div>
                </div>
            )}

            {/* Footer */}
            <div className="mt-20 pt-8 border-t border-slate-100 flex justify-between items-center opacity-30">
                <p className="text-[10px] font-bold tracking-widest uppercase">theprofessor.xyz / study / {data.title.toLowerCase().replace(/\s+/g, '-')}</p>
                <div className="w-10 h-10 rounded-lg bg-slate-900 flex items-center justify-center">
                    <div className="w-4 h-4 rounded-sm bg-[var(--accent)]" />
                </div>
            </div>
        </div>
    );
}
