import { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, Zap, Target, Book, Brain, Shield } from "lucide-react";
import BrandLogo from "@/components/ui/BrandLogo";

const examData: Record<string, any> = {
  jamb: {
    name: "JAMB (UTME) 2026",
    fullName: "Joint Admissions and Matriculation Board",
    description: "Dominate the 2026 UTME with AI-powered CBT simulations and syllabus-accurate retrieval practice.",
    color: "linear-gradient(135deg, #10B981 0%, #064E3B 100%)",
    hacks: [
      { title: "CBT Simulation", desc: "Practice in the exact interface of the JAMB CBT system." },
      { title: "Syllabus Mastery", desc: "AI-generated questions based on the latest 2026 JAMB syllabus." },
      { title: "Time Management", desc: "Strategic pacing tools to ensure you finish every subject with time to spare." }
    ],
    faqs: [
      { question: "How can AI help me pass JAMB?", answer: "AI identifies your weakest subjects (e.g., Use of English, Physics) and generates targeted questions to bridge those gaps before the exam day." },
      { question: "Is this based on the 2026 syllabus?", answer: "Yes, our systems are updated to reflect the specific curriculum and text requirements for the 2026 UTME cycle." }
    ]
  },
  waec: {
    name: "WAEC (WASSCE) 2026",
    fullName: "West African Examinations Council",
    description: "Scale your WASSCE preparation. Turn dense textbooks into actionable flashcards and mock essays.",
    color: "linear-gradient(135deg, #3B82F6 0%, #1E3A8A 100%)",
    hacks: [
      { title: "Essay Analysis", desc: "Use AI to grade your practice essays against WAEC's marking schemes." },
      { title: "Objective Practice", desc: "Thousands of past-question variations generated by AI." },
      { title: "Practical Guides", desc: "Condensed logic for Biology, Chemistry, and Physics practicals." }
    ],
    faqs: [
      { question: "Can AI help with WAEC Theory papers?", answer: "Yes, by providing structured outlines and key terminology that examiners look for in high-scoring scripts." }
    ]
  }
};

export async function generateMetadata({ params }: { params: { slug: string } }): Promise<Metadata> {
  const exam = examData[params.slug];
  if (!exam) return { title: "Exam Guide Not Found" };

  return {
    title: `Best AI for ${exam.name} Prep | The Professor AI Strategy`,
    description: exam.description,
    keywords: [`${exam.name} prep`, `${params.slug} ai tutor`, "jamb cbt practice", "waec revision"],
  };
}

export default function ExamLandingPage({ params }: { params: { slug: string } }) {
  const exam = examData[params.slug];
  if (!exam) notFound();

  return (
    <div className="min-h-screen bg-[var(--background)] text-[var(--foreground-secondary)] pt-24 pb-20">
      <div className="max-w-4xl mx-auto px-6">
        <header className="relative rounded-[40px] overflow-hidden p-8 md:p-16 mb-12" style={{ background: exam.color }}>
          <div className="absolute inset-0 opacity-10 bg-[radial-gradient(circle_at_50%_50%,white,transparent)]" />
          <div className="relative z-10 text-center">
            <h1 className="text-4xl md:text-6xl font-bold text-white mb-4">{exam.name}</h1>
            <p className="text-lg md:text-xl text-white/80 max-w-2xl mx-auto leading-relaxed">
              {exam.description}
            </p>
            <div className="mt-8 flex flex-wrap justify-center gap-4">
               <Link href="/signup" className="px-8 py-4 rounded-2xl bg-white text-black font-black uppercase tracking-widest hover:scale-105 transition-all">
                  Start Revision
               </Link>
            </div>
          </div>
        </header>

        <section className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-20">
          {exam.hacks.map((hack: any, i: number) => (
            <div key={i} className="p-6 rounded-3xl bg-white/[0.02] border border-white/5">
              <h3 className="text-lg font-bold text-white mb-2 flex items-center gap-2">
                 <Zap className="w-5 h-5 text-[var(--accent)]" /> {hack.title}
              </h3>
              <p className="text-sm text-white/40 leading-relaxed">
                {hack.desc}
              </p>
            </div>
          ))}
        </section>

        <section className="mb-20 p-8 md:p-12 rounded-[40px] border border-[var(--accent-glow)] bg-[var(--accent-bg)]/20">
           <h2 className="text-2xl font-bold text-white mb-6">Why Students Are Switching to AI</h2>
           <div className="space-y-6 text-white/60 leading-relaxed">
              <p>
                The 2026 exam cycle is more competitive than ever. Traditional past question booklets are outdated the moment they are printed. **The Professor AI** provides a living, breathing study ecosystem that adapts to your performance.
              </p>
              <ul className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                 <li className="flex items-center gap-3"><Shield className="w-4 h-4 text-[var(--accent)]" /> 100% Syllabus Alignment</li>
                 <li className="flex items-center gap-3"><Target className="w-4 h-4 text-[var(--accent)]" /> Zero Distraction Environment</li>
                 <li className="flex items-center gap-3"><Brain className="w-4 h-4 text-[var(--accent)]" /> Active Recall Workflows</li>
                 <li className="flex items-center gap-3"><Book className="w-4 h-4 text-[var(--accent)]" /> Instant Conceptual Clarity</li>
              </ul>
           </div>
        </section>

        <section className="mb-20">
           <h2 className="text-2xl font-bold text-white mb-8">Frequently Asked Questions</h2>
           <div className="space-y-4">
              {exam.faqs.map((faq: any, i: number) => (
                <div key={i} className="p-6 rounded-2xl bg-white/[0.02] border border-white/5">
                   <h3 className="font-bold text-white mb-2">{faq.question}</h3>
                   <p className="text-sm text-white/50">{faq.answer}</p>
                </div>
              ))}
           </div>
        </section>
      </div>
    </div>
  );
}
